- name: Verify variables are set
  assert:
    that: "{{ item }} is defined"
  with_items:
    - mr_provisioner_machine_name
    - mr_provisioner_kernel_description
    - mr_provisioner_initrd_description
    - mr_provisioner_kernel_path
    - mr_provisioner_initrd_path
    - mr_provisioner_url
    - mr_provisioner_auth_token
    - mr_provisioner_preseed_name
    - mr_provisioner_arch
    - mr_provisioner_subarch

- name: Upload Kernel image
  mr_provisioner_image:
    description: "{{ mr_provisioner_kernel_description }}"
    type: Kernel
    arch: "{{ mr_provisioner_arch }}"
    path: "{{ mr_provisioner_kernel_path }}"
    url: "{{ mr_provisioner_url }}"
    token: "{{ mr_provisioner_auth_token }}"
    public: true
  run_once: true
  register: kernel_image
- debug: var=kernel_image
- name: Upload Initrd image
  mr_provisioner_image:
    description: "{{ mr_provisioner_initrd_description }}"
    type: Initrd
    arch: "{{ mr_provisioner_arch }}"
    path: "{{ mr_provisioner_initrd_path }}"
    url: "{{ mr_provisioner_url }}"
    token: "{{ mr_provisioner_auth_token }}"
    public: true
  run_once: true
  register: initrd_image
- debug: var=initrd_image

- name: Upload Preseed
  mr_provisioner_preseed_upload_module:
          preseed_name: "{{ mr_provisioner_preseed_name }}"
          preseed_file: "{{ mr_provisioner_preseed_path }}"
          preseed_type: "{{ mr_provisioner_preseed_type }}"
          preseed_description: "{{ mr_provisioner_preseed_description|default('') }}"
          preseed_bknowngood: "{{ mr_provisioner_preseed_knowngood|default(False) }}"
          preseed_bpublic: "{{ mr_provisioner_preseed_public|default(False) }}"
          mrp_url: "{{ mr_provisioner_url }}"
          mrp_token: "{{ mr_provisioner_auth_token }}"
  run_once: true
  register: preseed_image
- debug: var=preseed_image

- name: Provision machine
  mr_provisioner_machine_provision:
    machine_name: "{{ mr_provisioner_machine_name }}"
    kernel_description: "{{ mr_provisioner_kernel_description }}"
    initrd_description: "{{ mr_provisioner_initrd_description }}"
    kernel_options: "{{ mr_provisioner_kernel_options|default('') }}"
    arch: "{{ mr_provisioner_arch }}"
    subarch: "{{ mr_provisioner_subarch }}"
    preseed_name: "{{ mr_provisioner_preseed_name }}"
    url: "{{ mr_provisioner_url }}"
    token: "{{ mr_provisioner_auth_token }}"
  register: provision_machine
- debug: var=provision_machine

- name: Get IP of provisioned machine
  mr_provisioner_get_ip:
    mrp_url: "{{ mr_provisioner_url }}"
    mrp_token: "{{ mr_provisioner_auth_token }}"
    machine_name: "{{ mr_provisioner_machine_name }}"
    interface_name: "{{ mr_provisioner_interface_name|default('eth1') }}"
  register: get_ip
- debug: var=get_ip

- name: Add provisioned machine as host
  add_host:
          name: "{{ get_ip['ip'] }}"
          groups: target
  when: get_ip['ip'] is defined
